name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Verificar se index.html existe
        run: |
          if [ ! -f public/index.html ]; then
            echo "❌ ERRO: O arquivo public/index.html não foi encontrado."
            exit 1
          fi

      - name: Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public